### ISSUE TITLE
[EPIC] new select product UI

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxwise#189]
Here is an [interactive walkthrough](https://xd.adobe.com/view/5b5416a4-680c-40dd-6351-20f6a85c8323-2d65/) for the new "select-product"-UI

### Work steps
- [ ] Icons #54 
- [ ] make categories user-manageable #57 
- [ ] add icons to products #187 
- [ ] create component for product-selection
- [ ] change UI in "add Boxes" and "Find Boxes"

<img width="1102" alt="screen shot 2018-06-08 at 14 38 09" src="https://user-images.githubusercontent.com/38283578/41158572-b725a0ea-6b29-11e8-99ba-50c40f998f64.png">
