### ISSUE TITLE
[Epic] Administration interface

### ISSUE THREAD

**Issue by bfirsh** [boxwise/boxwise#27]
Some things we need, off the top of my mind:

- [ ] A superuser flag on users that lets them manage organisations and other users
- [ ] An interface for managing users
- [ ] An interface for managing organisations
