### ISSUE TITLE
Create menu for product categories

### ISSUE THREAD

**Issue by barto74** [boxwise/boxwise#57]
Each product is part of an category, e.g. Spaghetti is part of the category Food. Until now, categories are hardcoded in `AddProductForm.js`. In the future they should be user manageable. 
Categories are used in the product select

## Implementation
- [ ] Categories just need to have a name and an icon for now.  Icons are to be created in #54. Feel free to make a dummy icon as long as the icon database is not ready yet.
- [ ] Create a menu similar to the "manage products" menu. I guess you can copy most of it.
- [ ] Add an "Add category"-menu. 
- [ ] Categories do not have to be editable or deletable for now. #190 
- [ ] The prior product data needs to be migrated/updated. (See #179)

**Comment by barto74** [comment]
See also #104.
The question is here: do we want to make the categories actually user manageable or not? Or do we want to have specific independent attributes for age groups and genders?

**Comment by HaGuesto** [comment]
@barto74 
To be more generic, categories and products should be user manageable.
However, if we want to optimize the UX,e.g. control the product selection process, probably they should not be user-manageable.

Adding the icons could be a good compromise to have a better UX and at the same time stay generic.

**Comment by HaGuesto** [comment]
Closed ("Paused") due to discussion #275.
