### ISSUE TITLE
Design changes in menu and header

### ISSUE THREAD

**Issue by barto74** [boxwise/boxwise#68]
### Tasks
- [ ] Hide always the Left menu (like on mobile)
- [ ] display Logo in header
- [ ] display Logout option in top right

**Comment by HaGuesto** [comment]
@barto74 Could these be issues for the Hackathon?

**Comment by barto74** [comment]
@HaGuesto yes

**Comment by YuanyeZ** [comment]
On it. (TA)

**Comment by HaGuesto** [comment]
@jamescrowley I think we should close this issue and discuss next meeting how our menu should look like.

I created a new issue for it #505
